stages:
  - build
  - test

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x

  function deploy() {
    docker rm  hb
    docker rmi hb
  }


before_script:
  - *auto_devops

.build_job:dev:
  variables:
    URL: "hb"
  script:
    - deploy
    - docker build -t hb .

build_job:
  extends:
    - .build_job:dev

master_job:
  stage: test
  only:
    refs:
      - master
  script:
    - docker run --name hb -d -p 9086:9086 hb
  when: manual
