stages:
  - build
  - test

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x

  function deploy() {
    echo "Restoring Packages... $1"
  }


before_script:
  - *auto_devops


.build_job:
  stage: build
  environment:
    name: master
  script:
    - echo "Release build..."
    - deploy 333
  except:
    - tags

.build_job:dev:
  variables:
    URL: "hb"
  script:
    - echo "Hello world! $URL"

build_job:
  extends:
    - .build_job
    - .build_job:dev

test_job:
  stage: test
  script:
    - echo "Tests run..."

master_job:
  stage: test
  only:
    refs:
      - master
  script:
    - echo "Tests run..."
  when: manual
