{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-ws
  labels:
    app: {{ template "appname" . }}-ws
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.websocketPort }}
    targetPort: {{ .Values.service.websocketPort }}
    protocol: TCP
    name: {{ .Values.service.name }}-websocket
  selector:
    app: {{ template "appname" . }}-ws
    release: {{ .Release.Name }}
    tier: "{{ .Values.application.tier }}"
{{- end -}}
